# Generated by Django 4.2.9 on 2024-01-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Charge"),
                    (2, "Purchase"),
                    (4, "Transfer sent"),
                    (3, "Transfer received"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="TransferTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="received_transfers",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "sender_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sent_transfers",
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
    ]
